import Globe from 'globe.gl';
import './style.css';
const typeName={ALL:'全部',MODEL:'模型',RESEARCH:'研究',PRODUCT:'产品',HARDWARE:'算力硬件',ROBOTICS:'机器人',POLICY:'政策监管',FUNDING:'融资',OPEN:'开源'};
const events=[
{id:1,city:'旧金山',country:'美国',lat:37.77,lng:-122.42,type:'MODEL',level:'CRITICAL',impact:97,trust:91,mins:8,title:'前沿多模态模型出现重大更新信号',summary:'多源信号指向模型能力、工具调用和多模态交互出现明显变化，可能对智能体生态与开发工具产生连锁影响。'},
{id:2,city:'北京',country:'中国',lat:39.90,lng:116.40,type:'MODEL',level:'CRITICAL',impact:94,trust:90,mins:22,title:'大型推理模型生态活跃度快速上升',summary:'模型发布、推理优化和产业适配信号同步增强，国内推理模型竞争进一步加速。'},
{id:3,city:'深圳',country:'中国',lat:22.54,lng:114.06,type:'ROBOTICS',level:'HIGH',impact:88,trust:87,mins:47,title:'具身智能与机器人量产信号增强',summary:'机器人本体、视觉语言动作模型与制造场景结合更加紧密，供应链活跃度明显上升。'},
{id:4,city:'东京',country:'日本',lat:35.68,lng:139.69,type:'ROBOTICS',level:'HIGH',impact:83,trust:84,mins:75,title:'机器人基础模型研究集群持续扩张',summary:'多家研究机构聚焦通用操作、空间理解与低样本学习，机器人基础模型进入加速验证阶段。'},
{id:5,city:'台北',country:'中国台湾',lat:25.03,lng:121.56,type:'HARDWARE',level:'CRITICAL',impact:92,trust:93,mins:138,title:'AI 加速器与先进封装链条持续升温',summary:'算力芯片、HBM、先进封装与服务器供应链活动同步增强，硬件仍是 AI 扩张关键约束。'},
{id:6,city:'西雅图',country:'美国',lat:47.60,lng:-122.33,type:'PRODUCT',level:'HIGH',impact:84,trust:86,mins:206,title:'企业级智能体编排平台加速落地',summary:'智能体从单点能力转向跨工具、跨数据源与工作流编排，企业部署强调可观测与权限治理。'},
{id:7,city:'伦敦',country:'英国',lat:51.50,lng:-0.12,type:'POLICY',level:'MEDIUM',impact:76,trust:92,mins:295,title:'新一轮人工智能治理框架进入审议',summary:'监管重点聚焦高风险模型、透明度、责任主体与模型安全评估。'},
{id:8,city:'巴黎',country:'法国',lat:48.86,lng:2.35,type:'RESEARCH',level:'MEDIUM',impact:73,trust:88,mins:360,title:'开放研究基准正在快速获得行业采用',summary:'评测重点从单项能力向推理、工具调用、可靠性和代理任务迁移。'},
{id:9,city:'新加坡',country:'新加坡',lat:1.35,lng:103.82,type:'FUNDING',level:'MEDIUM',impact:69,trust:82,mins:520,title:'区域 AI 基础设施投资强度持续上升',summary:'数据中心、算力与企业 AI 服务投资增加，区域算力格局出现新的增长节点。'},
{id:10,city:'班加罗尔',country:'印度',lat:12.97,lng:77.59,type:'OPEN',level:'MEDIUM',impact:72,trust:80,mins:690,title:'开源智能体框架生态加速扩张',summary:'围绕模型路由、工具协议、记忆和工作流的开源项目数量持续上升。'},
{id:11,city:'首尔',country:'韩国',lat:37.56,lng:126.98,type:'HARDWARE',level:'HIGH',impact:81,trust:89,mins:840,title:'存储与 AI 服务器产业链出现高活跃信号',summary:'高带宽存储、互联与整机系统成为近期高频信号。'},
{id:12,city:'多伦多',country:'加拿大',lat:43.65,lng:-79.38,type:'RESEARCH',level:'MEDIUM',impact:68,trust:84,mins:1100,title:'长上下文与记忆机制研究持续推进',summary:'研究热点开始转向有效记忆、压缩、检索与持续学习。'}];
let activeType='ALL',windowMins=1440,searchText='';
const arcs=[[events[0],events[5]],[events[0],events[4]],[events[1],events[2]],[events[4],events[3]],[events[6],events[7]],[events[8],events[9]],[events[10],events[4]]].map(pair=>({a:pair[0],b:pair[1]}));
const globe=Globe()(document.getElementById('globe')).backgroundColor('rgba(0,0,0,0)').globeImageUrl('/assets/earth-night.jpg').bumpImageUrl('/assets/earth-topology.png').showAtmosphere(true).atmosphereColor('#32dfff').atmosphereAltitude(.18).pointLat('lat').pointLng('lng').pointAltitude(d=>.045+d.impact/2500).pointRadius(d=>d.level==='CRITICAL'?.34:d.level==='HIGH'?.27:.19).pointColor(d=>d.level==='CRITICAL'?'#ff617d':d.level==='HIGH'?'#62f5ff':'#9c7cff').ringLat('lat').ringLng('lng').ringColor(d=>t=>d.level==='CRITICAL'?'rgba(255,97,125,'+(1-t)+')':'rgba(98,245,255,'+(1-t)+')').ringMaxRadius(d=>d.level==='CRITICAL'?6.7:4.7).ringPropagationSpeed(d=>d.level==='CRITICAL'?2.2:1.5).ringRepeatPeriod(d=>d.level==='CRITICAL'?700:1200).arcsData(arcs).arcStartLat(d=>d.a.lat).arcStartLng(d=>d.a.lng).arcEndLat(d=>d.b.lat).arcEndLng(d=>d.b.lng).arcColor(()=>['rgba(66,220,255,.08)','rgba(145,108,255,.62)']).arcDashLength(.45).arcDashGap(1.15).arcDashAnimateTime(3900).onPointClick(showDetail);
if(globe.showGraticules)globe.showGraticules(true);
try{const c=globe.controls();c.autoRotate=true;c.autoRotateSpeed=.24;c.enablePan=false;c.minDistance=170;c.maxDistance=520}catch{}
globe.pointOfView({lat:24,lng:55,altitude:2.0},0);
function visible(){return events.filter(d=>{const q=(d.city+' '+d.country+' '+d.title+' '+typeName[d.type]).toLowerCase();return(activeType==='ALL'||d.type===activeType)&&d.mins<=windowMins&&(!searchText||q.includes(searchText))}).sort((a,b)=>b.impact-a.impact)}
function timeText(m){if(m<60)return m+' 分钟前';if(m<1440)return Math.floor(m/60)+' 小时前';return Math.floor(m/1440)+' 天前'}
function refresh(){const a=visible();globe.pointsData(a).ringsData(a.filter(d=>d.level!=='MEDIUM'));renderFeed(a);document.getElementById('signalCount').textContent=Math.max(12,a.length*12+Math.floor(Math.random()*5))}
function renderFeed(a){const box=document.getElementById('feed');box.innerHTML='';a.slice(0,6).forEach(d=>{const el=document.createElement('div');el.className='event '+(d.level==='CRITICAL'?'critical':d.level==='HIGH'?'high':'');const lv=d.level==='CRITICAL'?'重大':d.level==='HIGH'?'高影响':'关注';el.innerHTML='<div class="event-meta"><span><span class="kind">'+typeName[d.type]+'</span> · '+d.city+'</span><span class="level">'+lv+'</span></div><h3>'+d.title+'</h3><div class="event-foot"><span>'+timeText(d.mins)+'</span><span>影响 '+d.impact+'</span><span>可信 '+d.trust+'</span></div>';el.onclick=()=>showDetail(d);box.appendChild(el)})}
function showDetail(d){try{globe.controls().autoRotate=false}catch{}globe.pointOfView({lat:d.lat,lng:d.lng,altitude:1.35},800);document.getElementById('detailMeta').textContent=typeName[d.type]+' · '+d.city+' / '+d.country+' · '+timeText(d.mins);document.getElementById('detailTitle').textContent=d.title;document.getElementById('detailText').textContent=d.summary+' 当前为视觉原型模拟数据。';document.getElementById('impactNum').textContent=d.impact;document.getElementById('trustNum').textContent=d.trust;document.getElementById('impactBar').style.width=d.impact+'%';document.getElementById('trustBar').style.width=d.trust+'%';document.getElementById('detail').classList.add('show')}
document.getElementById('close').onclick=()=>{document.getElementById('detail').classList.remove('show');try{globe.controls().autoRotate=true}catch{}};
const f=document.getElementById('filters');Object.keys(typeName).forEach(t=>{const d=document.createElement('div');d.className='filter'+(t==='ALL'?' on':'');d.innerHTML='<span>'+typeName[t]+'</span><i></i>';d.onclick=()=>{activeType=t;document.querySelectorAll('.filter').forEach(x=>x.classList.remove('on'));d.classList.add('on');refresh()};f.appendChild(d)});
document.getElementById('search').oninput=e=>{searchText=e.target.value.trim().toLowerCase();refresh();const a=visible();if(a.length&&searchText)globe.pointOfView({lat:a[0].lat,lng:a[0].lng,altitude:1.55},650)};
document.querySelectorAll('#ranges button').forEach(b=>b.onclick=()=>{windowMins=+b.dataset.min;document.querySelectorAll('#ranges button').forEach(x=>x.classList.remove('on'));b.classList.add('on');refresh()});
setInterval(()=>{const v=(85.8+Math.random()*1.4).toFixed(1);document.getElementById('pulseVal').textContent=v;document.getElementById('activity').textContent=Math.round(v)},4200);
setInterval(()=>document.getElementById('clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'}),1000);
refresh();